---
title: "distance to health centre"
author: "Julia Jaeger"
date: "2026-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages 
pacman::p_load(
  rio, janitor, lubridate, skimr, epikit, gtsummary, here,
  tidyverse, knitr, flextable, tibble, epitools, readxl, sf,
  terra, ggspatial, ggplot2, mdsr, spData, readr, leaflet,
  gganimate, plotly, stringi, gt, officer, tinytex, ggrepel,
  reactable, MASS, broom, openxlsx, dplyr, bslib, htmltools
)
```

```{r}
health_map <- st_read(here("data/camp_facility_data.shp")) %>% 
  clean_names() %>% 
  filter(facility_t %in% c("Health Post", "Primary Health Center") )
  
sub_blocks <- st_read(here("data/camp_majhi_subblock_boundary/camp_majhi_subblock_boundary.shp"))
  filter(site_name %in% c("Camp 14", "Camp 15 (Jamtoli)", "Camp 16"))
         
# Spatial join: assign each facility to the camp polygon it falls inside
facilities_with_camps <- st_join(health_map, sub_blocks, join = st_intersects, left = FALSE)

# shapefile for camp boundaries and block boundaries
camp_block <- st_read(here("data/Block_Boundary_V1/Block_Boundary_V1.shp")) %>% 
  clean_names() %>% 
  filter(camp_name_1 %in% c("Camp 14", "Camp 15", "Camp 16")) %>% 
  mutate(
    camp_name_1 = case_when(
      camp_name_1 == "Camp 15" ~ "Camp 15 (Jamtoli)",
      TRUE ~ camp_name_1
    ))

# summarize camp boundaries
camp <- camp_block %>% 
  group_by(camp_name_1) %>%
  summarise(
    geometry = sf::st_union(geometry),
    .groups = "drop"
  )
#summarize block boundaries
blocks <- camp_block %>% 
  group_by(camp_name_1, block_label) %>%
  summarise(
    geometry = sf::st_union(geometry),
    .groups = "drop"
  )

# calculate subblock prevalence 
rdt_done <- read.csv(here("data/rdt_done.csv")) %>% 
  mutate(
    # 1. Camp: extract digits after "C" and prepend "Camp"
    camp_nr = paste0("Camp ", str_extract(camp, "(?<=C)\\d+")),

    # 2. Block: extract the second capital letter (after the space)
    block = str_extract(camp, "(?<=\\s)[A-Z]"),

    # 3. Sub-block: keep only the letter + first number(s), drop after dash
    sub_block = str_extract(camp, "(?<=\\s)[A-Z]\\d+"),

    # Step 2: remove leading zero after the letter
    sub_block = str_replace(sub_block, "([A-Z])0+(\\d+)", "\\1\\2")
  ) 

rdt_done <- read.csv(here("data/rdt_done.csv")) %>% 
  mutate(
    # 1. Camp: extract digits after "C" and prepend "Camp"
    camp_nr = paste0("Camp ", str_extract(camp, "(?<=C)\\d+")),

    # 2. Block: extract the second capital letter (after the space)
    block = str_extract(camp, "(?<=\\s)[A-Z]"),

    # 3. Sub-block: keep only the letter + first number(s), drop after dash
    sub_block = str_extract(camp, "(?<=\\s)[A-Z]\\d+"),

    # Step 2: remove leading zero after the letter
    sub_block = str_replace(sub_block, "([A-Z])0+(\\d+)", "\\1\\2")
  ) %>% 
  mutate(
    camp_nr = case_when(
      camp_nr == "Camp 15" ~ "Camp 15 (Jamtoli)",
      TRUE ~ camp_nr
    ),
    # Special case: if Camp 15 (Jamtoli) and block == "C", then sub_block should be "E" + number
    sub_block = case_when(
      camp_nr == "Camp 15 (Jamtoli)" & block == "C" ~ str_replace(sub_block, "^C", "E"),
      TRUE ~ sub_block
    )
  ) 

# identify replicates and remove - keep the positive pcr 
rdt_done <- rdt_done %>%
  mutate(
    duplicate_flag = duplicated(patient_id) | duplicated(patient_id, fromLast = TRUE)
  )   %>% 
  group_by(patient_id) %>%
  # Special case: keep all if patient_id is blank
  filter(
    patient_id == "" |
      # Otherwise keep only one row per patient_id
      (
        # If any Positive exists, keep only Positive
        (any(rdt_positive == "Positive") & rdt_positive == "Positive") |
        # If no Positive, keep the first occurrence
        (!any(rdt_positive == "Positive") & row_number() == 1)
      )
  ) %>%
  ungroup()


# create startified datasets
# age groups 
rdt_done <- rdt_done %>%
  filter(!is.na(age),
         sex %in% c("Male", "Female")) %>%   # drop "Other (sex)"
  mutate(
    age_group = case_when(
      age < 14  ~ "<14",
      age >= 14 & age <= 17 ~ "14–17",
      age >= 18 & age <= 24 ~ "18–24",
      age >= 25 & age <= 34 ~ "25–34",
      age >= 35 & age <= 44 ~ "35–44",
      age >= 45 & age <= 54 ~ "45–54",
      age >= 55             ~ "55+",
      TRUE ~ NA_character_
    )
  )

# sex and age groups  for blocks 
summary_camp_block <- rdt_done %>%
  filter(rdt_done == 1) %>%
  group_by(camp_nr, block, age_group, sex) %>%
  summarise(
    tested     = n(),
    positives  = sum(rdt_positive == "Positive ", na.rm = TRUE),
    prevalence = positives / tested * 100,
    .groups = "drop"
  )

# sex and age groups for subblocks 
summary_camp_block_sub <- rdt_done %>%
  filter(rdt_done == 1) %>%
  group_by(camp_nr, block, sub_block, age_group, sex) %>%
  summarise(
    tested     = n(),
    positives  = sum(rdt_positive == "Positive ", na.rm = TRUE),
    prevalence = positives / tested * 100,
    .groups = "drop"
  )


# calculate number of peopel tested, number of people positive and nr. of people negative 
summary_total <- rdt_done %>%
  group_by(camp, block, sub_block) %>%
  summarise(
    # Count RDT done vs not done
    rdt_done_yes = sum(rdt_done == 1, na.rm = TRUE),
    rdt_done_no  = sum(rdt_done == 0, na.rm = TRUE),

    # Count RDT results
    rdt_positive = sum(rdt_positive == "Positive ", na.rm = TRUE),
    rdt_negative = sum(rdt_positive == "Negative ", na.rm = TRUE),
    .groups = "drop"
  )

# merge with sub_block data set and calculate prevalence
```

```{r}
# merge with shapefiles
# merge block with camp_block and sub_block with sub_blocks
prevalence_subblock <- sub_blocks %>% 
  left_join(summary_camp_block_sub, by = c(
    "site_name"   = "camp_nr",
    "block_name"  = "block",
    "subblock_n"  = "sub_block"
  )) %>%
  mutate(
    prevalence = ifelse(
      tested > 0,
      (positives / tested) * 100,
      NA_real_
    )
  ) %>% 
  filter()

prevalence_subblock <- prevalence_subblock %>%
  filter(!is.na(age_group), !is.na(sex))
```


```{r plotting}
 sero_prevalence <- ggplot() +
  # Sub-block polygons filled by prevalence
  geom_sf(data = prevalence_subblock %>% filter(sex == "Male"), aes(fill = prevalence), color = "grey30", size = 0.3) +

  # Block outlines
  geom_sf(data = sub_blocks %>% group_by(block_name) %>% summarise(), 
          color = "black", fill = NA) +

  # Camp outlines
  geom_sf(data = sub_blocks %>% group_by(site_name) %>% summarise(), 
          color = "black", fill = NA) +

  # Facilities
  geom_sf(data = facilities_with_camps, aes(color = facility_t), size = 2) +

  # Facet by age group (rows) and sex (columns)
  facet_grid(~ age_group) +

  scale_fill_gradient(
    low = "white",
    high = "red", 
    na.value = "grey80", 
    name = "Prevalence (%)"
  ) +
  scale_color_manual(values = c("Health Post" = "red", "Primary Health Center" = "blue")) +

  theme_minimal() +
  labs(color = "Facility Type",
       title = "Health Facilities and Prevalence by Age Group and Sex") +

  # Theme adjustments
  theme(
    strip.text = element_text(size = 14, face = "bold"),   # bigger, bold facet labels
    axis.text = element_blank(),                          # remove axis text
    axis.ticks = element_blank(),                         # remove axis ticks
    panel.grid = element_blank(),                          # remove grid lines
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 18, face = "bold")
  )

sero_prevalence 
# Save directly, since sero_prevalence is your ggplot object
ggsave("prevalence_map_subblock_male.png", plot = sero_prevalence, width = 12, height = 12, dpi = 300)

  
```


```{r}
# merge with shapefiles
# merge block with camp_block and sub_block with sub_blocks
prevalence_block <- camp_block %>% 
  left_join(summary_camp_block, by = c(
    "camp_name_1"   = "camp_nr",
    "block_label"  = "block"
  )) %>%
  mutate(
    prevalence = ifelse(
      tested > 0,
      (positives / tested) * 100,
      NA_real_
    )
  ) %>% 
  filter()

prevalence_block <- prevalence_block %>%
  filter(!is.na(age_group), !is.na(sex))
```


```{r plotting}
 sero_prevalence <- ggplot() +
  # Sub-block polygons filled by prevalence
  geom_sf(data = prevalence_block %>% filter(sex == "Male"), aes(fill = prevalence), color = "grey30", size = 0.3) +

  # Block outlines
  geom_sf(data = camp , 
          color = "black", fill = NA, size = 1) +

  # Camp outlines
  geom_sf(data = blocks,
          color = "black", fill = NA) +

  # Facilities
  geom_sf(data = facilities_with_camps, aes(color = facility_t), size = 2) +

  # Facet by age group (rows) and sex (columns)
  facet_wrap(~ age_group) +

  scale_fill_gradient(
    low = "white",
    high = "red", 
    na.value = "grey80", 
    name = "Prevalence (%)"
  ) +
  scale_color_manual(values = c("Health Post" = "red", "Primary Health Center" = "blue")) +

  theme_minimal() +
  labs(color = "Facility Type",
       title = "Health Facilities and Prevalence by Age Group and Sex") +

  # Theme adjustments
  theme(
    strip.text = element_text(size = 14, face = "bold"),   # bigger, bold facet labels
    axis.text = element_blank(),                          # remove axis text
    axis.ticks = element_blank(),                         # remove axis ticks
    panel.grid = element_blank(),                          # remove grid lines
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 18, face = "bold")
  )
  
sero_prevalence
# Save directly, since sero_prevalence is your ggplot object
ggsave("prevalence_map_block_male.png", plot = sero_prevalence, width = 8, height = 12, dpi = 300)

  
```

```{r}
# Viral prevalence

prevalence_blocks <- tribble(
  ~Camp,      ~Block, ~PCR_Positive, ~RDT_Done, ~Viramic_prevalence,
  "Camp 14",  "A",    275,           2924,      9.40,
  "Camp 14",  "B",    229,           2807,      8.16,
  "Camp 14",  "C",    364,           2685,      13.56,
  "Camp 14",  "D",    407,           2813,      14.47,
  "Camp 14",  "E",    488,           3702,      13.18,
  
  "Camp 15",  "A",    342,           2269,      15.07,
  "Camp 15",  "B",    308,           2078,      14.82,
  "Camp 15",  "C",    210,           2830,      7.42,
  "Camp 15",  "D",    579,           4786,      12.10,
  "Camp 15",  "E",    579,           4641,      12.48,
  "Camp 15",  "F",    380,           3831,      9.92,
  "Camp 15",  "G",    263,           3402,      7.73,
  "Camp 15",  "H",    1002,          4130,      24.26,
  
  "Camp 16",  "A",    479,           3579,      13.38,
  "Camp 16",  "B",    374,           2387,      15.67,
  "Camp 16",  "C",    227,           1934,      11.74,
  "Camp 16",  "D",    381,           2907,      13.11
)

viral_prev <- blocks %>% 
  left_join(prevalence_blocks, by = c(
    "camp_name_1" = "Camp",
    "block_label" = "Block"
  ))

ggplot() +
  # Block polygons (filled by prevalence, outlined)
  geom_sf(data = viral_prev, aes(fill = Viramic_prevalence), color = "grey30", size = 0.5) +

  # Camp outlines (no fill, just boundaries)
  geom_sf(data = Camp, color = "black", fill = NA, size = 1) +

  # Facilities inside those camps
  geom_sf(data = facilities_with_camps, aes(color = facility_t), size = 2) +

  # White to red gradient, NA shown as grey
  scale_fill_gradient(
    low = "white",
    high = "red", 
    na.value = "grey80", 
    name = "Prevalence"
  ) +

  scale_color_manual(values = c("Health Post" = "red", "Primary Health Center" = "blue")) +
  theme_minimal() +
  labs(color = "Facility Type",
       title = "Viral Prevalence in Camps 14, 15, and 16")


# Calculate centroids for labeling

```

