---
title: Measles Dashboard - OCB
subtitle: Cox's Bazaar - April 2026

project:
  output-dir: docs

format: 
  dashboard:
    orientation: columns
    theme: yeti
---

```{r load packages}
#| message: false
# Load packages 
pacman::p_load(
  rio, janitor, lubridate, skimr, epikit, gtsummary, here,
  tidyverse, knitr, flextable, tibble, epitools, readxl, sf,
  terra, ggspatial, ggplot2, mdsr, spData, readr, leaflet,
  gganimate, plotly, stringi, gt, officer, tinytex, ggrepel,
  reactable, MASS, broom, openxlsx, dplyr, bslib, htmltools
)
```

```{r import data}
# case data
measles_data <- read.csv(here("data/measels_data.csv"), sep = ";") %>%  
  clean_names() %>% 
  dplyr::select(-c(2, 3, 6, 7, 9, 10, 18:20, 23:52, 54:62, 64:100 )) %>% 
  mutate(
    camp = if_else(
      camp == "Other",
      specify_other_camp,
      camp
    )
  ) %>% 
  dplyr::select(-specify_other_camp) %>% 
  mutate(
    block = str_remove(block, "^Block\\s+")
  ) %>% 
  mutate(
    camp = if_else(
      camp == "KTP Register Camp", "Kutupalong RC",
      camp
    )
  ) %>% 
  mutate(
    camp = case_when(
      camp %in% c("Camp 1", "Camp 8") ~ paste0(camp, "E"),
      TRUE ~ camp
    )
  ) %>% 
  mutate(
    enter_a_date = as.Date(enter_a_date, format = "%Y-%m-%d")
  )

#map data
sub_blocks <- st_read(here("data/Block_Boundary_V1/Block_Boundary_V1.shp"), quiet = TRUE) %>% 
  filter(!CampName_1 %in% c("Camp 21", "Camp 22", "Camp 24", "Camp 25", "Camp 26", "Camp 27", "Nayapara RC"))

#merge datasets
cases_sf <- measles_data %>%
  left_join(
    sub_blocks,
    by = c("camp" = "CampName_1",
           "block" = "BlockLabel"
           )
  ) %>%
  st_as_sf()

# points for map
cases_points <- cases_sf %>%
  filter(!is.na(District)) %>% 
  mutate(
    geometry = map(
      geometry,
      ~ st_sample(.x, size = 1) %>% st_cast("POINT")
    )
  ) %>%
  unnest(geometry) %>%
  st_as_sf() %>%
  st_set_crs(st_crs(sub_blocks))


camp_boundaries <- sub_blocks %>%
  group_by(CampName_1) %>%
  summarise(
    geometry = sf::st_union(geometry),
    .groups = "drop"
  )

epi_cases <- measles_data %>%
  filter(!is.na(enter_a_date)) %>%
  arrange(enter_a_date) %>%
  group_by(enter_a_date) %>%
  mutate(
    case_id = row_number(),
    hover_text = paste0(
      "Sex: ", gender, "<br>",
      "Age: ", age_in_years, " years<br>"
    )
  ) %>%
  ungroup()
```

```{r calculate numbers}
# Total cases
total_cases <- nrow(measles_data)

# Severe cases
severe_cases <- measles_data %>%
  filter(clinical_severity == "Severe") %>%
  nrow()

# Simple cases
simple_cases <- measles_data %>%
  filter(clinical_severity == "Simple") %>%
  nrow()

# Weekly cases (last 7 days)
weekly_cases <- measles_data %>%
  filter(enter_a_date >= Sys.Date() - 7) %>%
  nrow()

# Weekly severe cases
weekly_severe_cases <- measles_data %>%
  filter(enter_a_date >= Sys.Date() - 7,
         clinical_severity == "Severe") %>%
  nrow()

# Weekly simple cases
weekly_simple_cases <- measles_data %>%
  filter(enter_a_date >= Sys.Date() - 7,
         clinical_severity == "Simple") %>%
  nrow()

# Yesterday's cases
yesterdays_cases <- measles_data %>%
  filter(enter_a_date == Sys.Date() - 1) %>%
  nrow()

# Yesterday's severe cases
yesterdays_severe_cases <- measles_data %>%
  filter(enter_a_date == Sys.Date() - 1,
         clinical_severity == "Severe") %>%
  nrow()

# Yesterday's simple cases
yesterdays_simple_cases <- measles_data %>%
  filter(enter_a_date == Sys.Date() - 1,
         clinical_severity == "Simple") %>%
  nrow()
```

```         
```

## Column {.tabset width="40%"}

```{r first map}
#| title: "Cases Severity"
#| fig.asp: 1
#| out.width: 100%
#| fig.align: center
#| fig.margin: 0
map_dots <- ggplot() +
  geom_sf(
    data = sub_blocks,
    fill = "white",
    color = "grey80",
    linewidth = 0.1
  ) + 
geom_sf(
    data = camp_boundaries,
    fill = NA,
    color = "black",
    linewidth = 0.7
  ) +
  geom_sf(
    data = cases_points,
    aes(color = clinical_severity),
    size = 3,
    alpha = 0.7
  ) +
  coord_sf(expand = FALSE) +
  theme_light() +
  theme(
    plot.margin = margin(0, 0, 0, 0),
    panel.spacing = unit(0, "pt"),
    panel.background = element_rect(fill = "white", color = NA)
  ) +
  labs(
       color = "Clinical severity") +
  theme(plot.title = element_text(face = "bold", size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
        axis.text.y = element_text(angle = 45, hjust = 1, size = 14),
        legend.title = element_text(face = "bold", size = 18),
        legend.text = element_text(size = 16)) +
  theme(
  panel.border = element_blank(),
  panel.background = element_blank(),
  plot.background = element_blank()
)


print(map_dots)
```

```{r second map}
#| title: "Treatment Place"
#| fig.asp: 1
#| out.width: 100%
#| fig.align: center
#| fig.margin: 0
second_map_dots <- ggplot() +
  geom_sf(
    data = sub_blocks,
    fill = "white",
    color = "grey80",
    linewidth = 0.1
  ) + 
geom_sf(
    data = camp_boundaries,
    fill = NA,
    color = "black",
    linewidth = 0.7
  ) +
  geom_sf(
    data = cases_points,
    aes(color = phc),
    size = 3,
    alpha = 0.7
  ) +
  coord_sf(expand = FALSE) +
  theme_light() +
  theme(
    plot.margin = margin(0, 0, 0, 0),
    panel.spacing = unit(0, "pt"),
    panel.background = element_rect(fill = "white", color = NA)
  ) +
  labs(
       color = "Place of Treatment") +
  theme(plot.title = element_text(face = "bold", size = 22),
        plot.subtitle = element_text(size = 18),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
        axis.text.y = element_text(angle = 45, hjust = 1, size = 14),
        legend.title = element_text(face = "bold", size = 18),
        legend.text = element_text(size = 16)) +
  theme(
  panel.border = element_blank(),
  panel.background = element_blank(),
  plot.background = element_blank()
)

print(second_map_dots)
```

## Column {width="60%"}

### Row {height="23%"}

```{r values 1}
div(
  style = "background-color:white; padding:0px; border-radius:0px; font-size:14px;",
  div(span(strong("Total Cases: "), total_cases),
  div(span(strong("Weekly Cases: "), weekly_cases),
  div(span(strong("Yesterday's Cases: "), yesterdays_cases),
      style = "border-bottom:1px solid black; padding-bottom:2px;")
)))
```

```{r values 2}
div(
  style = "background-color:white; padding:0px; border-radius:0px; font-size:14px;",
  div(
    span(strong("Severe Cases: "), severe_cases),
    div(
      span(strong("Weekly Severe Cases: "), weekly_severe_cases),
      div(
        span(strong("Yesterday's Severe Cases: "), yesterdays_severe_cases),
        style = "border-bottom:1px solid black; padding-bottom:2px;"
      )
    )
  )
)
```

```{r values 3}
div(
  style = "background-color:white; padding:0px; border-radius:0px; font-size:14px;",
  div(
    span(strong("Simple Cases: "), simple_cases),
    div(
      span(strong("Weekly Simple Cases: "), weekly_simple_cases),
      div(
        span(strong("Yesterday's Simple Cases: "), yesterdays_simple_cases),
        style = "border-bottom:1px solid black; padding-bottom:2px;"
      )
    )
  )
)
```

### Row {height="77%"}

```{r values 4}
#| padding: 0px
epi_curve <- ggplot(
  epi_cases,
  aes(x = enter_a_date, y = case_id, fill = clinical_severity, text = hover_text)
) +
  geom_tile(
    width = 0.9,
    height = 0.9,
    color = "black"
  ) +
  scale_x_date(
    date_breaks = "1 day",
    date_labels = "%d %b",
    expand = c(0, 0)
  ) +
  labs(
    title = "Epidemic curve – measles",
    subtitle = "April 03.04 - 26.04",
    x = "Date",
    y = "Cases",
    fill = "Clinical severity"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.margin = margin(5, 5, 5, 5)
  )


epi_curve_interactive <- ggplotly(
  epi_curve,
  tooltip = "text"
) %>%
  config(displayModeBar = FALSE)

epi_curve_interactive
```
